INSERT INTO contract_key (ckey,TYPE_id,time_type_id,description) VALUES
                            (100,1,1,"ORDINARIO"),
                            (109,1,1,"FOMENTO CONTRATACIÓN INDEFINIDA TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (130,1,1,"PERSONAS CON DISCAPACIDAD"),
                            (139,1,1,"PERSONAS CON DISCAPACIDAD TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (150,1,1,"FOMENTO CONTRATACIÓN INDEFINIDA INICIAL"),
                            (189,1,1,"TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (200,1,2,"ORDINARIO"),
                            (209,1,2,"FOMENTO CONTRATACIÓN INDEFINIDA TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (230,1,2,"PERSONAS CON DISCAPACIDAD"),
                            (239,1,2,"PERSONAS CON DISCAPACIDAD TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (250,1,2,"FOMENTO CONTRATACIÓN INDEFINIDA INICIAL"),
                            (289,1,2,"TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (300,1,3,""),
                            (309,1,3,"FOMENTO CONTRATACIÓN INDEFINIDA TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (330,1,3,"PERSONAS CON DISCAPACIDAD"),
                            (339,1,2,"PERSONAS CON DISCAPACIDAD TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (350,1,3,"FOMENTO CONTRATACIÓN INDEFINIDA INICIAL"),
                            (389,1,3,"TRANSFORMACIÓN CONTRATO TEMPORAL"),
                            (401,2,1,"OBRA O SERVICIO DETERMINADO"),
                            (402,2,1,"EVENTUAL CIRCUNSTANCIAS DE LA PRODUCCIÓN"),
                            (408,3,1,"CARÁCTER ADMINISTRATIVO"),
                            (410,2,1,"INTERINIDAD"),
                            (418,2,1,"INTERINIDAD CARÁCTER ADMINISTRATIVO"),
                            (420,3,1,"PRÁCTICAS"),
                            (421,3,1,"FORMACIÓN Y APRENDIZAJE"),
                            (430,3,1,"PERSONAS CON DISCAPACIDAD"),
                            (441,3,1,"RELEVO"),
                            (450,3,1,"FOMENTO CONTRATACIÓN INDEFINIDA"),
                            (452,3,1,"EMPRESAS DE INSERCIÓN"),
                            (501,2,2,"OBRA O SERVICIO DETERMINADO"),
                            (502,2,2,"EVENTUAL CIRCUNSTANCIAS DE LA PRODUCCIÓN"),
                            (508,3,2,"CARÁCTER ADMINISTRATIVO"),
                            (510,2,2,"INTERINIDAD"),
                            (518,2,2,"INTERINIDAD CARÁCTER ADMINISTRATIVO"),
                            (520,3,2,"PRÁCTICAS"),
                            (530,3,2,"PERSONAS CON DISCAPACIDAD"),
                            (540,3,2,"JUBILADO PARCIAL"),
                            (541,3,2,"RELEVO"),
                            (550,3,2,"FOMENTO CONTRATACIÓN INDEFINIDA"),
                            (552,3,2,"EMPRESAS DE INSERCIÓN");