INSERT INTO process_type (TYPE) VALUES
                            ("ALTA"),("BAJA"),("ANULACION_ALTA_PREVIA"),("ANULACION_ALTA_CONSOLIDADA"),
                            ("ANULACION_BAJA_PREVIA"), ("ANULACION_BAJA_CONSOLIDADA"), ("CAMBIO_CONTRATO_CONSOLIDADO"), ("CAMBIO_CONTRATO_PREVIO"),("CONSULTA_IPF"),
                            ("CONSULTA_NAF"),("CONSULTA_ALTAS_CCC"),("CONSULTA_TA"),("CONSULTA_ALTA")